### ISSUE TITLE
genTest.tcl file missing

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/TritonCTS#2]
Hi,
Are you missing anything in documentation? Like where do we point to def or lef ? 
I am guessing the below files needs to be updated for proper inputs
soce_config.tcl
verilog_preprocess.py
update_def.py 

In anycase, I did ran run_all.tcl and get below error. Can you please help? I think documentation and location of below file is grossly missing...

anaghavsd@rise:~/Desktop/work/tools/TritonCTS/src/genLUT$ ./run_all.tcl 
cp: cannot stat './template/genTest.tcl': No such file or directory
    while executing
"exec cp -rf ./template/genTest.tcl $dir/ "
    ("foreach" body line 15)
    invoked from within
"foreach dist $distList {
    set dir "test_${dist}_${unit_dist}_${NDR}"

    set numbuf_loc [expr int(($dist)/$unit_dist)]
    set totNum [expr pow(2,..."
    (file "./run_all.tcl" line 12)

**Comment by mpfogaca** [comment]
Hi. Thanks very much for reporting the problem. We will work to improve our documentation.

**Comment by mpfogaca** [comment]
Closes #2
