### ISSUE TITLE
missing separator error while compiling

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/TritonCTS#4]
Hi
As mentioned in earlier issue, you asked to do make in root directory. But when I do so, I get missing separator error like below:

anaghavsd@rise:/Desktop/work/tools/TritonCTS$ make
Makefile:1: *** missing separator.  Stop.
anaghavsd@rise:/Desktop/work/tools/TritonCTS$ 

Am I missing something?

**Comment by mpfogaca** [comment]
Hi, @kunalg123.

The syntax issue is solved.

-- Mateus
