### ISSUE TITLE
make fatal error: ilcplex/ilocplex.h: No such file or directory

### ISSUE THREAD

**Issue by kunalg123** [abk-openroad/TritonCTS#5]
Hi,
Thanks for updating
I am getting new error while doing make:

anaghavsd@rise:~/Desktop/work/tools/TritonCTS$ make
g++ -m64 -O3 -std=c++11 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD -Wno-ctor-dtor-privacy -fopenmp  -I/home/tool/ilog/CPLEX_Studio1251/cplex/include -I/home/tool/ilog/CPLEX_Studio1251/concert/include  -g  -o bin/argument.o \
 -c src/ghtree/argument.cpp 
g++ -m64 -O3 -std=c++11 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD -Wno-ctor-dtor-privacy -fopenmp  -I/home/tool/ilog/CPLEX_Studio1251/cplex/include -I/home/tool/ilog/CPLEX_Studio1251/concert/include  -g  -o bin/tree.o \
 -c src/ghtree/tree.cpp 
g++ -m64 -O3 -std=c++11 -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD -Wno-ctor-dtor-privacy -fopenmp  -I/home/tool/ilog/CPLEX_Studio1251/cplex/include -I/home/tool/ilog/CPLEX_Studio1251/concert/include  -g  -o bin/design.o \
 -c src/ghtree/design.cpp 
src/ghtree/design.cpp:59:30: fatal error: ilcplex/ilocplex.h: No such file or directory
compilation terminated.
Makefile:81: recipe for target 'bin/design.o' failed
make: *** [bin/design.o] Error 1

**Comment by mpfogaca** [comment]
Hi, @kunalg123.

Do you have CPLEX installed in your system? In the affirmative case, can you try to update the paths CPLEXLIBDIR and CONCERTLIBDIR in the makefile?

Thanks,
-- Mateus

**Comment by kunalg123** [comment]
Hi
No, I haven't installed it
Looks like it's only for institutes. Can it be uploaded on Triton CTS
installation page? Any other way for companies to download it?

**Comment by mpfogaca** [comment]
Hi, @kunalg123.

At this moment we have this dependency which is IBM proprietary (i.e. we cannot distribute by ourselves). 

-- Mateus
