### ISSUE TITLE
Incorrect python version specified in README

### ISSUE THREAD

**Issue by tajayi** [abk-openroad/TritonCTS#7]
The README claims it requires python 2.7 but it appears to require 3.x. 

Additionally, it would be helpful to delete the deprecated use of `from statistics import median`. The package is not available on michigan/anaconda and has to be installed separately.

Thanks

**Comment by mpfogaca** [comment]
Hi, Tutu.

Thanks for reporting this! I've updated the python scripts and now TritonCTS works properly with Python 2.7.x!

The change is in the dev branch for now. After testing I'll merge with the main branch.

Regards,
-- Mateus
