### ISSUE TITLE
TritonCTS portability issues

### ISSUE THREAD

**Issue by tajayi** [abk-openroad/TritonCTS#8]
In general, the tool is not very portable. I think a good way to "run" a program like this is something like:
```tritonCts -config ./objects/aesConfig -lutFile ./objects/lut-65.txt -solFile ./objects/sol_list-65.txt -tritonCTSDir OpenROAD/TritonCTS -outputDir ./results/```
Where the tools can be invoked from any directory. That being said, I'm working on some workarounds since I know this isn't high priority

I do have a few things I've changed in order to get things to work with out test environment without being too intrusive
1. I am building an "export" of the tool. See this docker image for reference steps. Essentially the folder can be copied anywhere and then executed similar to other OpenROAD tools. see the docker file [here](https://github.com/The-OpenROAD-Project/CI/blob/master/build/docker/cts/Dockerfile)
1. Third-party apps are not copied from your repo. FlexRoute, RePlAce and nutplace* are built separately and present in $PATH during execution. Where is lefdef2cts and pd_rev coming from? Also pd_rev doesn't appear to be used
1. Right now, we have issues with the "-plot" option of RePlAce so I need that disabled
1. Adding she-bangs in the python script instead of the "python" command. (Allows a mix of python scripts)
1. I've pushed my changes to a umich branch so that I can easily do the builds/testing. We can talk about if you want to integrated them to master later or how to handle it.

Thanks again

**Comment by mpfogaca** [comment]
Hi, Tutu.

- Thanks for the feedback. We are aware of most of these problems. I've uploaded a new script called "runTritonCTS.tcl" in the development branch (bc8b779085283bd2148e56ec0b0992bce39f7bee). It has all the features you asked, check the usage:

./runTritonCTS.tcl -configFilePath=../cts.cfg -scriptsPath=../src/scripts -techFilesPath=../src/tech -lefDefParserPath=../third_party/lefdef2cts -executablePath=../bin/genHtree -replacePath=../third_party/RePlAce -legalizerPath=../third_party/ntuplace4h -outputPath=customPathResults2

.. If you do not specify any of the parameters, CTS will adopt the current behavior.

- We will also move from GNU make to Cmake in the next few days.

- Some binaries are not open-sourceable at this moment :-(

- All improvements are most welcome! :-)

Thanks again,
-- Mateus

**Comment by tajayi** [comment]
Can you please let me know when this is ready to test?

**Comment by mpfogaca** [comment]
You can download and test from the development branch.

$ git checkout dev

**Comment by tajayi** [comment]
This issue has been resolved with the latest updates.

Thanks!
