### ISSUE TITLE
How to determine skew, tolerance and sinks for cts run?

### ISSUE THREAD

**Issue by tajayi** [abk-openroad/TritonCTS#9]
Initially when running cts, genHtree was always reporting "No solutions found" causing the entire tool to fail. It wasn't until we put in just the right skew number before it successfully ran. Can you provide guidiance on how to automatically derive the skew, tolerance and sink arguements that should be sent to the tool? Or perhaps a safe number that's expected to run for many designs.

Presently I've tried a bunch of numbers with another design with no luck.

Thanks

**Comment by mpfogaca** [comment]
Hi, Tutu.

Thanks for your message. Right now we are working to make these parameters automatic inside the tool.

Depending on design size, I recommend:
- Trying different skew numbers, varying from 5, 10, 15... to 150;
- Also combine with 128, 256 and 512 num_sinks;
- Use toler=0 unless you see runtime issues. Then I recomment trying 1000.

Thanks again,
-- Mateus

**Comment by tajayi** [comment]
Currently, we have an automated way to try to test many test cases/designs (10+) so it's not very practical for use to do a sweep of all the variables. 
In addition, at the integration exercise (or when we start letting more people use it) it would be weird to tell users to perform a wide range of permutations.

Is it possible to try to calculate skew based on timing reports from synth? Is it possible to calculate sinks from looking at the number of components on the clock net? Same for tolerance...

I'm not sure what these variables represent and how they are used in the tool, so some documentation would be appreciated. Ideally we would want to perform more QoR analysis and it would be best to have the settings that deliver the best performance.

Thanks

**Comment by mpfogaca** [comment]
Hi, Tutu.

Please understand that this tool is originated from academic scripts for research and we are working to improve it.

Once you have the tool calibrated for one design (... and you have our config file for 16), it is easy to setup for other designs.

-- Mateus

**Comment by tajayi** [comment]
This issue has been resolved with the latest updates.

Thanks!
